export const CONFIG_TIMER = "CONFIG_TIMER";
export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const RESET_TIMER = "RESET_TIMER";
export const EXHAUSTED_TIMER = "EXHAUSTED_TIMER";
export const RAISE_CLEAR_ALARM_TIMER = "RAISE_CLEAR_ALARM_TIMER";
